name: Publish to NPM

on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: Publish on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: |
          yarn install --frozen-lockfile
      
      - name: Publish
        run: |
          yarn run publish
        env:
          GITHUB_TOKEN: ${{ github.token }}